In [1]:
import tensorflow as tf
tf.__version__

'2.15.0'

In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
## sentences
sent = ["the glass of milk",
    "the glass of juice",
    "the cup of tea",
    "I am a good boy",
    "I am a good developer",
    "understand the meaning of words",
    "not every word has a meaning"]

In [4]:
vocab_size = 10000

In [5]:
## One hot representation
one_hot_repr = [one_hot(words, vocab_size) for words in sent]
print(one_hot_repr)

[[6575, 9963, 4935, 4686], [6575, 9963, 4935, 7273], [6575, 4042, 4935, 426], [5003, 7944, 2306, 2895, 6194], [5003, 7944, 2306, 2895, 857], [3142, 6575, 6380, 4935, 5059], [1024, 5598, 9954, 5801, 2306, 6380]]


In [6]:
## word embedding
from tensorflow.keras.layers import Embedding
from tensorflow.keras.models import Sequential
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np

In [7]:
sent_length = 8
embedded_docs = pad_sequences(one_hot_repr, padding='pre', maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 6575 9963 4935 4686]
 [   0    0    0    0 6575 9963 4935 7273]
 [   0    0    0    0 6575 4042 4935  426]
 [   0    0    0 5003 7944 2306 2895 6194]
 [   0    0    0 5003 7944 2306 2895  857]
 [   0    0    0 3142 6575 6380 4935 5059]
 [   0    0 1024 5598 9954 5801 2306 6380]]


In [8]:
dim = 10
model = Sequential()
model.add(Embedding(vocab_size, dim, input_length=sent_length))
model.compile('adam', 'mse')

In [9]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [10]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 495ms/step
[[[ 1.81651376e-02 -6.22056425e-04  4.34203036e-02 -1.39463656e-02
   -4.80805412e-02 -2.34359987e-02 -4.58119772e-02 -1.75750479e-02
    1.62908770e-02 -1.65385120e-02]
  [ 1.81651376e-02 -6.22056425e-04  4.34203036e-02 -1.39463656e-02
   -4.80805412e-02 -2.34359987e-02 -4.58119772e-02 -1.75750479e-02
    1.62908770e-02 -1.65385120e-02]
  [ 1.81651376e-02 -6.22056425e-04  4.34203036e-02 -1.39463656e-02
   -4.80805412e-02 -2.34359987e-02 -4.58119772e-02 -1.75750479e-02
    1.62908770e-02 -1.65385120e-02]
  [ 1.81651376e-02 -6.22056425e-04  4.34203036e-02 -1.39463656e-02
   -4.80805412e-02 -2.34359987e-02 -4.58119772e-02 -1.75750479e-02
    1.62908770e-02 -1.65385120e-02]
  [ 2.81858929e-02  3.93229835e-02  4.38818224e-02  3.37742008e-02
   -5.85556030e-03  2.79035233e-02  2.55013369e-02 -4.45210710e-02
   -3.98679376e-02  1.49696954e-02]
  [-2.49006283e-02  8.28637928e-03  3.98909785e-02 -3.84532213e-02
   -4.18663025e-03 -1.97100639

In [11]:
embedded_docs[0]

array([   0,    0,    0,    0, 6575, 9963, 4935, 4686])

In [12]:
model.predict(embedded_docs)[0]

1/1 [==============================] - 0s 64ms/step


array([[ 0.01816514, -0.00062206,  0.0434203 , -0.01394637, -0.04808054,
        -0.023436  , -0.04581198, -0.01757505,  0.01629088, -0.01653851],
       [ 0.01816514, -0.00062206,  0.0434203 , -0.01394637, -0.04808054,
        -0.023436  , -0.04581198, -0.01757505,  0.01629088, -0.01653851],
       [ 0.01816514, -0.00062206,  0.0434203 , -0.01394637, -0.04808054,
        -0.023436  , -0.04581198, -0.01757505,  0.01629088, -0.01653851],
       [ 0.01816514, -0.00062206,  0.0434203 , -0.01394637, -0.04808054,
        -0.023436  , -0.04581198, -0.01757505,  0.01629088, -0.01653851],
       [ 0.02818589,  0.03932298,  0.04388182,  0.0337742 , -0.00585556,
         0.02790352,  0.02550134, -0.04452107, -0.03986794,  0.0149697 ],
       [-0.02490063,  0.00828638,  0.03989098, -0.03845322, -0.00418663,
        -0.00197101, -0.02858853, -0.03567172,  0.02384367,  0.0454532 ],
       [ 0.00414492, -0.02906859,  0.03798248,  0.02714925, -0.03887307,
         0.04366729,  0.02722844, -0.03880686